### ISSUE TITLE
Latest version

### ISSUE THREAD

**Issue by ran9898** [parse-community/ParseUI-Android#158]
What should I write instead of the - "latest.version.here" in the dependencies - 
implementation "com.github.parse-community.ParseUI-Android:widget:latest.version.here"

Thanks

**Comment by flovilmart** [comment]
0.0.5 at the time of writing. It’s written on the README, on the 1st line, on the jitpack shield. It’s also the most recent tag and the most recent release.

Hope you’ll never have to ask such question again
